spring:
  profiles:
    active: dev
    include:
      - base-addi
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  batch:
    job:
      names: ${job.name:NONE}
      enabled: false
    jdbc:
      initialize-schema: ALWAYS
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true
        use_sql_comments: true
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    root: info
    com.ll.exam.mutBook.app: debug
    org.hibernate.type.descriptor.sql: trace
custom:
  order:
    cancelAvailableSeconds: 600
  rebate:
    wholesalePriceRate: 0.5
  site:
    name: M-BOOKS
    baseUrl: "http://localhost:8010"
